// Generated by tatamuc from mdlite — do not edit.
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'dart:ffi';

class Mdlite {
  final DynamicLibrary _lib;
  Mdlite(this._lib);

  /// Load from a dynamic library file (Android .so, desktop .dylib/.dll).
  factory Mdlite.open(String path) => Mdlite(DynamicLibrary.open(path));

  /// Use symbols linked into the process (iOS static lib / XCFramework).
  factory Mdlite.process() => Mdlite(DynamicLibrary.process());

  late final md_alloc = _lib.lookupFunction<Pointer<Uint8> Function(UintPtr), Pointer<Uint8> Function(int)>('md_alloc');
  late final md_free = _lib.lookupFunction<Void Function(Pointer<Uint8>, UintPtr), void Function(Pointer<Uint8>, int)>('md_free');
  late final md_to_html = _lib.lookupFunction<Pointer<Uint8> Function(Pointer<Uint8>, UintPtr, Pointer<UintPtr>), Pointer<Uint8> Function(Pointer<Uint8>, int, Pointer<UintPtr>)>('md_to_html');

  ({Pointer<Uint8> ptr, int len}) writeString(String s) {
    final bytes = utf8.encode(s);
    final ptr = md_alloc(bytes.length);
    ptr.asTypedList(bytes.length).setAll(0, bytes);
    return (ptr: ptr, len: bytes.length);
  }

  String readString(Pointer<Uint8> ptr, int len) => utf8.decode(ptr.asTypedList(len));

  /// Read a returned (ptr, out_len) string and free the buffer.
  /// Pair this with exports of the form: `fn f(...) -> *mut u8` + `out_len *mut usize`.
  String takeString(Pointer<Uint8> ptr, int len) {
    final s = readString(ptr, len);
    md_free(ptr, len);
    return s;
  }

  /// Allocate scratch space for an out-param (e.g. `out_len *mut usize`).
  Pointer<UintPtr> allocLenSlot() => md_alloc(sizeOf<UintPtr>()).cast<UintPtr>();

  /// Read a usize out-param. Pointer<UintPtr> has no direct .value extension,
  /// so read as Uint64 (all supported ABIs — arm64 / x86_64 — are 64-bit).
  int readLenSlot(Pointer<UintPtr> p) => p.cast<Uint64>().value;

  void freeLenSlot(Pointer<UintPtr> p) => md_free(p.cast<Uint8>(), sizeOf<UintPtr>());
}
